use_frameworks!

platform :ios, '9.0'

target 'HCFullscreenPopGesture_Example' do
  pod 'HCFullscreenPopGesture', :path => '../'

  target 'HCFullscreenPopGesture_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
